# Header
menu:
  소개: /about
  블로그: /
  Github: https://www.github.com/marpple
#  Archives: /archives
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
#sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.ico
logo: //s3.marpple.co/s/5/marpple2/img/f_w_logo.png
twitter:
google_plus:
fb_admins:
fb_app_id:
